# ai-service/app/knowledge/portfolio.py
# Loads portfolio knowledge from portfolio_data.json, which is generated by
# the frontend build step (scripts/export-knowledge.ts via vite-node).
#
# To update the AI's knowledge: edit frontend/src/content/*, then run
# `npm run dev` or `npm run build` from the frontend directory, then restart uvicorn.
#
# The dataclasses below exist only so prompt_builder.py can use typed attributes.
# They are populated from JSON — no data lives in this file.

from __future__ import annotations

import json
import logging
from dataclasses import dataclass, field
from pathlib import Path
from typing import List, Optional

logger = logging.getLogger("ai.knowledge")

_JSON_PATH = Path(__file__).parent / "portfolio_data.json"


@dataclass
class ContactInfo:
    name: str
    title: str
    email: str
    phone: str
    location: str
    timezone: str
    response_time: str
    availability: str
    site_url: str
    resume_url: str
    calendly_url: str
    github: str
    linkedin: str


@dataclass
class CareerEntry:
    role: str
    company: str
    period: str
    current: bool
    highlights: List[str]
    technologies: List[str]


@dataclass
class ProjectMetric:
    label: str
    value: str
    description: Optional[str] = None


@dataclass
class Project:
    title: str
    tagline: str
    description: str
    category: str
    year: int
    role: str
    outcome: str
    technologies: List[str]
    metrics: List[str]  # "label: value" strings for prompt_builder compatibility


@dataclass
class SkillEntry:
    name: str
    category: str
    level: str
    years: int
    context: str


@dataclass
class Service:
    title: str
    tagline: str
    description: str
    deliverables: List[str]
    engagement: str
    duration: str


@dataclass
class FaqEntry:
    question: str
    answer: str


@dataclass
class PortfolioKnowledge:
    contact: ContactInfo
    bio: str
    tagline: str
    years_of_experience: int
    career: List[CareerEntry]
    projects: List[Project]
    skills: List[SkillEntry]
    services: List[Service]
    faq: List[FaqEntry]


# ── Loader ────────────────────────────────────────────────────────────────────

def _load() -> PortfolioKnowledge:
    if not _JSON_PATH.exists():
        raise FileNotFoundError(
            f"portfolio_data.json not found at {_JSON_PATH}. "
            "Run `npm run dev` or `npm run build` from the frontend directory first."
        )

    with open(_JSON_PATH, encoding="utf-8") as f:
        d = json.load(f)

    summary = d["summary"]
    contact_raw = summary["contact"]

    contact = ContactInfo(
        name=summary["name"],
        title=summary["title"],
        email=contact_raw["email"],
        phone=contact_raw.get("phone", ""),
        location=contact_raw.get("location", ""),
        timezone=contact_raw.get("timezone", ""),
        response_time=contact_raw.get("responseTime", ""),
        availability=contact_raw.get("availabilityText", contact_raw.get("availability", "")),
        site_url=contact_raw.get("siteUrl", ""),
        resume_url=contact_raw.get("resumeUrl", ""),
        calendly_url=contact_raw.get("calendlyUrl", ""),
        github=contact_raw.get("github", ""),
        linkedin=contact_raw.get("linkedin", ""),
    )

    career = [
        CareerEntry(
            role=e["role"],
            company=e["company"],
            period=f"{e.get('startDate', '')} – {e.get('endDate', 'Present') if not e.get('current') else 'Present'}",
            current=e.get("current", False),
            highlights=e.get("highlights", []),
            technologies=e.get("technologies", []),
        )
        for e in d.get("career", [])
    ]

    projects = [
        Project(
            title=p["title"],
            tagline=p.get("tagline", ""),
            description=p.get("description", ""),
            category=p.get("category", ""),
            year=p.get("year", 0),
            role=p.get("role", ""),
            outcome=p.get("outcome", ""),
            technologies=p.get("technologies", []),
            metrics=[
                f"{m['label']}: {m['value']}"
                for m in p.get("metrics", [])
            ],
        )
        for p in d.get("projects", [])
    ]

    skills = [
        SkillEntry(
            name=s["name"],
            category=s.get("category", ""),
            level=s.get("level", ""),
            years=s.get("yearsOfExperience", 0),
            context=s.get("context", ""),
        )
        for g in d.get("skillCategories", [])
        for s in g.get("skills", [])
    ]

    services = [
        Service(
            title=s["title"],
            tagline=s.get("tagline", ""),
            description=s.get("description", ""),
            deliverables=s.get("deliverables", []),
            engagement=s.get("engagement", ""),
            duration=s.get("duration", ""),
        )
        for s in d.get("services", [])
    ]

    faq = [
        FaqEntry(question=f["question"], answer=f["answer"])
        for f in d.get("faq", [])
    ]

    return PortfolioKnowledge(
        contact=contact,
        bio=summary.get("bio", ""),
        tagline=summary.get("tagline", ""),
        years_of_experience=summary.get("yearsOfExperience", 0),
        career=career,
        projects=projects,
        skills=skills,
        services=services,
        faq=faq,
    )


# ── Mtime-aware cache ────────────────────────────────────────────────────────
# Reloads from disk only when portfolio_data.json has been modified.
# No uvicorn restart needed — just run `npm run dev` from the frontend.

_cached_knowledge: Optional[PortfolioKnowledge] = None
_cached_mtime: float = 0.0


def get_knowledge() -> PortfolioKnowledge:
    global _cached_knowledge, _cached_mtime
    try:
        mtime = _JSON_PATH.stat().st_mtime
    except FileNotFoundError:
        raise FileNotFoundError(
            f"portfolio_data.json not found at {_JSON_PATH}. "
            "Run `npm run dev` or `npm run build` from the frontend directory first."
        )
    if _cached_knowledge is None or mtime != _cached_mtime:
        logger.info("[knowledge] Reloading portfolio_data.json (mtime changed)")
        _cached_knowledge = _load()
        _cached_mtime = mtime
    return _cached_knowledge


# Keep PORTFOLIO_KNOWLEDGE for any direct imports that still reference it.
PORTFOLIO_KNOWLEDGE: PortfolioKnowledge = get_knowledge()
