import type { Project } from '@/types'
import { GITHUB_URL } from '@/config/portfolio.config'

export const PROJECTS: Project[] = [
  {
    id: 'multitenant-saas-platform',
    slug: 'multitenant-saas-platform',
    title: 'Multi-Tenant SaaS Platform',
    tagline: 'One deployment. Eight enterprise clients. Zero data leakage.',
    description: 'A Spring Boot 3 backend serving 8 enterprise clients from a single deployment, with per-tenant data isolation enforced at the database layer via PostgreSQL row-level security — not application code.',
    category: 'enterprise',
    status: 'completed',
    featured: true,
    year: 2024,
    duration: '6 months',
    role: 'Lead Architect & Engineer',
    problem: 'The client was running 8 separate deployments of the same application — one per enterprise customer. Every bug fix required 8 deployments. Every schema migration ran 8 times. Infrastructure costs were scaling linearly with clients instead of logarithmically.',
    approach: 'Designed a shared-schema multi-tenancy model using PostgreSQL row-level security policies. Each API request sets a session-level tenant context variable; RLS policies filter all queries automatically. Spring Boot\'s filter chain injects the tenant ID from the JWT before any repository call. Zero application-layer tenant checks needed.',
    outcome: 'Reduced infrastructure cost by 65%. Deployment time dropped from 4 hours (8 sequential deploys) to 18 minutes (1 deploy). Onboarding a new enterprise client went from 3 weeks of DevOps work to a 4-minute database operation.',
    reflection: 'The hardest part wasn\'t the RLS policies — it was convincing the team that shared-schema was safe. The answer was a comprehensive test suite that proved isolation held under concurrent load.',
    tech: [
      { name: 'Java 21',       color: '#f89820' },
      { name: 'Spring Boot 3', color: '#6db33f' },
      { name: 'PostgreSQL',    color: '#336791' },
      { name: 'Vue 3',         color: '#42b883' },
      { name: 'AWS ECS',       color: '#ff9900' },
      { name: 'Docker',        color: '#2496ed' },
      { name: 'Jenkins',       color: '#d33833' },
      { name: 'Redis',         color: '#dc382d' },
    ],
    links: [
      { label: 'GitHub', url: GITHUB_URL, type: 'github' },
    ],
    metrics: [
      { label: 'Cost reduction',    value: '65%',   description: 'Infrastructure cost vs 8 separate deployments' },
      { label: 'Deploy time',       value: '18min', description: 'Down from 4 hours across 8 environments'       },
      { label: 'Enterprise clients',value: '8',     description: 'Served from a single deployment'               },
      { label: 'Onboarding time',   value: '4min',  description: 'New client provisioning via DB operation'      },
    ],
    order: 1,
  },
  {
    id: 'llm-document-pipeline',
    slug: 'llm-document-pipeline',
    title: 'LLM Document Processing Pipeline',
    tagline: 'GPT-4o + Spring Batch. 70% less manual review.',
    description: 'An AI-assisted pipeline that ingests unstructured legal and financial documents, extracts structured data using OpenAI function calling, validates against business rules, and routes exceptions to human reviewers — all orchestrated by Spring Batch.',
    category: 'backend',
    status: 'completed',
    featured: true,
    year: 2024,
    duration: '3 months',
    role: 'Backend Engineer & AI Integration Lead',
    problem: 'A legal services firm was spending 40 hours/week manually extracting data from contracts and financial statements. The documents were inconsistently formatted, came from 12 different sources, and had to be cross-referenced against a compliance database before any downstream processing.',
    approach: 'Built a Spring Batch pipeline with three phases: (1) document ingestion and normalisation via Apache Tika, (2) structured extraction using GPT-4o function calling with a strict JSON schema, (3) rule-based validation with confidence scoring. Documents below a confidence threshold are routed to a human review queue. Embeddings stored in pgvector enable semantic deduplication.',
    outcome: 'Manual review time dropped by 70%. The pipeline processes 500+ documents per day with 94% straight-through rate. The remaining 6% that reach human review are genuinely ambiguous — not false positives from a brittle regex.',
    reflection: 'Token cost was the main engineering constraint. Chunking strategy and prompt compression reduced per-document cost by 60% without accuracy loss. The lesson: LLM integration is mostly an economics problem.',
    tech: [
      { name: 'Java 21',       color: '#f89820' },
      { name: 'Spring Batch',  color: '#6db33f' },
      { name: 'OpenAI API',    color: '#10a37f' },
      { name: 'PostgreSQL',    color: '#336791' },
      { name: 'pgvector',      color: '#336791' },
      { name: 'Apache Tika',   color: '#e84e4e' },
      { name: 'Docker',        color: '#2496ed' },
      { name: 'AWS Lambda',    color: '#ff9900' },
    ],
    links: [
      { label: 'GitHub', url: GITHUB_URL, type: 'github' },
    ],
    metrics: [
      { label: 'Manual review reduction', value: '70%',  description: 'Hours saved per week'                    },
      { label: 'Daily throughput',         value: '500+', description: 'Documents processed per day'            },
      { label: 'Straight-through rate',    value: '94%',  description: 'Documents requiring no human review'   },
      { label: 'Token cost reduction',     value: '60%',  description: 'Via chunking and prompt optimisation'  },
    ],
    order: 2,
  },
  {
    id: 'realtime-logistics-platform',
    slug: 'realtime-logistics-platform',
    title: 'Real-Time Logistics Tracking',
    tagline: '50,000 shipment events per day. Sub-200ms p99.',
    description: 'A Kafka-backed event streaming platform for real-time shipment tracking across a logistics network of 200+ vehicles. Event sourcing for the order lifecycle enables full audit trails and replay capability.',
    category: 'backend',
    status: 'completed',
    featured: true,
    year: 2022,
    duration: '8 months',
    role: 'Senior Backend Engineer — Architecture Owner',
    problem: 'The existing system polled a GPS database every 30 seconds per vehicle. With 200+ vehicles, that was 400+ queries per minute on a single PostgreSQL instance that was already struggling. Location updates were 30–90 seconds stale. A major enterprise client was threatening to leave over SLA violations.',
    approach: 'Replaced polling with a Kafka event stream. GPS devices publish location events to a partitioned topic (partitioned by vehicle ID for ordering guarantees). Spring Boot consumers maintain materialised state in Redis for sub-millisecond reads. PostgreSQL receives only persisted state changes, not every event. Event sourcing on the order aggregate enables full replay for debugging and compliance.',
    outcome: 'Location staleness dropped from 30–90s to under 3s. Database load reduced by 85%. The enterprise client renewed their contract. p99 API latency for location queries: 180ms.',
    reflection: 'The event sourcing decision was controversial — it added complexity. But when a client needed to reconstruct the exact state of an order 6 months ago for a legal dispute, it paid for itself in one afternoon.',
    tech: [
      { name: 'Java 11',       color: '#f89820' },
      { name: 'Apache Kafka',  color: '#a0a0a0' },
      { name: 'Spring Boot',   color: '#6db33f' },
      { name: 'PostgreSQL',    color: '#336791' },
      { name: 'Redis',         color: '#dc382d' },
      { name: 'Kubernetes',    color: '#326ce5' },
      { name: 'AWS EKS',       color: '#ff9900' },
      { name: 'Gradle',        color: '#02303a' },
    ],
    links: [
      { label: 'GitHub', url: GITHUB_URL, type: 'github' },
    ],
    metrics: [
      { label: 'Location staleness', value: '<3s',  description: 'Down from 30–90 seconds'              },
      { label: 'DB load reduction',  value: '85%',  description: 'Queries eliminated by event streaming' },
      { label: 'Daily events',       value: '50K+', description: 'Shipment events processed per day'    },
      { label: 'p99 latency',        value: '180ms',description: 'Location query API response time'     },
    ],
    order: 3,
  },
  {
    id: 'payroll-compliance-engine',
    slug: 'payroll-compliance-engine',
    title: 'Payroll Compliance Engine',
    tagline: '₹40 Cr/month. 40+ statutory rules. Zero miscalculations.',
    description: 'A configurable payroll calculation engine handling Indian statutory compliance across 6 states — EPFO, ESIC, TDS, PT — for 12 enterprise clients. Replaced a brittle Excel-based process that had caused two payroll errors in the previous year.',
    category: 'enterprise',
    status: 'completed',
    featured: false,
    year: 2020,
    duration: '5 months',
    role: 'Software Engineer — Backend Lead',
    problem: 'Payroll was calculated in Excel by a team of 4 accountants. The spreadsheets had grown to 15,000 rows with circular references and undocumented macros. Two calculation errors in 12 months had resulted in incorrect salaries for 340 employees and significant reputational damage with enterprise clients.',
    approach: 'Modelled each statutory rule as a composable, testable Java function. A rule engine evaluates applicable rules per employee based on state, salary band, and employment type. Spring Batch processes the full payroll run in parallel chunks. Each calculation step is logged with inputs and outputs for full auditability. Integration with EPFO/ESIC/TDS APIs via a resilient adapter with retry and circuit breaker.',
    outcome: 'Zero payroll errors since deployment. Month-end batch processing time: 45 minutes (down from 6 hours manual). New client onboarding: 4 days (down from 3 weeks). The system has processed ₹40 Cr+ monthly without a single statutory compliance failure.',
    reflection: 'The most important architectural decision was making every calculation step auditable. When an employee disputes their salary, you need to show exactly which rules applied and why. That requirement shaped the entire data model.',
    tech: [
      { name: 'Java 8',        color: '#f89820' },
      { name: 'Spring Boot',   color: '#6db33f' },
      { name: 'Spring Batch',  color: '#6db33f' },
      { name: 'Oracle DB',     color: '#f80000' },
      { name: 'Redis',         color: '#dc382d' },
      { name: 'Maven',         color: '#c71a36' },
      { name: 'Jenkins',       color: '#d33833' },
      { name: 'REST APIs',     color: '#6366f1' },
    ],
    links: [
      { label: 'GitHub', url: GITHUB_URL, type: 'github' },
    ],
    metrics: [
      { label: 'Monthly transactions', value: '₹40Cr', description: 'Processed without errors'                  },
      { label: 'Batch processing',     value: '45min', description: 'Down from 6 hours manual'                  },
      { label: 'Compliance rules',     value: '40+',   description: 'Across 6 Indian states'                    },
      { label: 'Onboarding time',      value: '4 days',description: 'New enterprise client setup'               },
    ],
    order: 4,
  },
  {
    id: 'payment-reconciliation-engine',
    slug: 'payment-reconciliation-engine',
    title: 'Payment Reconciliation Engine',
    tagline: '100K records/day. 99.97% accuracy. Built from scratch.',
    description: 'A transaction reconciliation system matching 100,000+ daily payment records across 3 payment gateways. Idempotency keys and distributed locking eliminated duplicate charge incidents. Built as the sole backend engineer on a 12-person fintech startup.',
    category: 'backend',
    status: 'completed',
    featured: false,
    year: 2018,
    duration: '4 months',
    role: 'Junior Backend Engineer — Sole Owner',
    problem: 'The startup was manually reconciling payment records in spreadsheets every morning. Duplicate charges had occurred twice, costing ₹2L in refunds and damaging trust with early enterprise clients. The manual process took 3 hours daily and was error-prone under time pressure.',
    approach: 'Built a reconciliation engine that fetches settlement reports from 3 gateway APIs, normalises them to a canonical format, and matches against internal transaction records using a multi-pass algorithm (exact match → fuzzy match → exception queue). Idempotency keys on all payment operations prevent duplicate processing. Redis distributed locks prevent race conditions during concurrent reconciliation runs.',
    outcome: '99.97% reconciliation accuracy on first pass. Zero duplicate charge incidents since deployment. Daily reconciliation time: 8 minutes automated vs 3 hours manual. The system caught a gateway-side duplicate charge bug that would have cost ₹4L before it was noticed.',
    reflection: 'This was my first production system built alone. The thing I got wrong: I optimised for correctness before performance. The thing I got right: I optimised for correctness before performance.',
    tech: [
      { name: 'Java 8',      color: '#f89820' },
      { name: 'Spring MVC',  color: '#6db33f' },
      { name: 'PostgreSQL',  color: '#336791' },
      { name: 'Redis',       color: '#dc382d' },
      { name: 'Maven',       color: '#c71a36' },
      { name: 'REST APIs',   color: '#6366f1' },
      { name: 'JUnit',       color: '#25a162' },
      { name: 'Git',         color: '#f05032' },
    ],
    links: [
      { label: 'GitHub', url: GITHUB_URL, type: 'github' },
    ],
    metrics: [
      { label: 'Daily records',    value: '100K+',  description: 'Payment records reconciled per day'     },
      { label: 'Accuracy',         value: '99.97%', description: 'First-pass reconciliation accuracy'     },
      { label: 'Time saved',       value: '3hrs/day',description: 'Automated vs manual reconciliation'   },
      { label: 'Duplicate charges',value: '0',      description: 'Since idempotency implementation'      },
    ],
    order: 5,
  },
]

export const PROJECT_CATEGORY_CONFIG: Record<string, { label: string; color: string; bg: string; icon: string }> = {
  enterprise: { label: 'Enterprise', color: '#6366f1', bg: 'rgba(99,102,241,0.1)',  icon: 'pi pi-building'    },
  backend:    { label: 'Backend',    color: '#10b981', bg: 'rgba(16,185,129,0.1)',  icon: 'pi pi-server'      },
  cloud:      { label: 'Cloud',      color: '#f59e0b', bg: 'rgba(245,158,11,0.1)',  icon: 'pi pi-cloud'       },
  fullstack:  { label: 'Full Stack', color: '#06b6d4', bg: 'rgba(6,182,212,0.1)',   icon: 'pi pi-desktop'     },
  frontend:   { label: 'Frontend',   color: '#8b5cf6', bg: 'rgba(139,92,246,0.1)', icon: 'pi pi-palette'     },
}

export const PROJECT_GRADIENT: Record<string, { from: string; to: string; glow: string }> = {
  enterprise: { from: '#6366f1', to: '#8b5cf6', glow: 'rgba(99,102,241,0.25)'  },
  backend:    { from: '#10b981', to: '#06b6d4', glow: 'rgba(16,185,129,0.25)'  },
  cloud:      { from: '#f59e0b', to: '#ef4444', glow: 'rgba(245,158,11,0.25)'  },
  fullstack:  { from: '#06b6d4', to: '#6366f1', glow: 'rgba(6,182,212,0.25)'   },
  frontend:   { from: '#8b5cf6', to: '#ec4899', glow: 'rgba(139,92,246,0.25)'  },
}
