import type { Service } from '@/types'

export const SERVICES: Service[] = [
  {
    id: 'fullstack-development',
    title: 'Full Stack Development',
    tagline: 'End-to-end product delivery — from DB schema to deployed UI.',
    description: 'I own the full vertical: Spring Boot APIs, Vue 3 frontend, PostgreSQL schema, AWS infrastructure, and CI/CD pipeline. You get one engineer who can make decisions across the entire stack without handoff delays.',
    icon: 'pi pi-desktop',
    deliverables: [
      { text: 'Spring Boot 3 + Vue 3 application' },
      { text: 'PostgreSQL schema with migrations' },
      { text: 'AWS ECS/Fargate deployment' },
      { text: 'Jenkins CI/CD pipeline' },
      { text: 'Technical documentation' },
    ],
    engagement: 'project',
    duration: '4–16 weeks',
    featured: true,
    highlighted: true,
    badge: 'Most Popular',
    order: 1,
  },
  {
    id: 'backend-apis',
    title: 'Backend API Development',
    tagline: 'Production-grade REST APIs built for scale and correctness.',
    description: 'Spring Boot 3 APIs with proper error handling (RFC 7807), JWT auth, rate limiting, pagination, and OpenAPI docs. Built to handle real load — not just happy-path demos.',
    icon: 'pi pi-server',
    deliverables: [
      { text: 'RESTful API with OpenAPI 3 spec' },
      { text: 'JWT authentication & authorisation' },
      { text: 'Redis caching & rate limiting' },
      { text: 'Integration test suite (>80% coverage)' },
      { text: 'Postman collection for all endpoints' },
    ],
    engagement: 'project',
    duration: '2–8 weeks',
    featured: true,
    highlighted: false,
    order: 2,
  },
  {
    id: 'frontend-development',
    title: 'Frontend Development',
    tagline: 'Vue 3 interfaces that are fast, accessible, and maintainable.',
    description: 'Component-driven Vue 3 frontends with TypeScript, Pinia state management, and GSAP animations. Performance-first: lazy loading, code splitting, and Core Web Vitals optimisation built in from day one.',
    icon: 'pi pi-palette',
    deliverables: [
      { text: 'Vue 3 + TypeScript SPA' },
      { text: 'Pinia state management' },
      { text: 'Responsive design (mobile-first)' },
      { text: 'WCAG 2.1 AA accessibility' },
      { text: 'Core Web Vitals optimisation' },
    ],
    engagement: 'project',
    duration: '2–6 weeks',
    featured: false,
    highlighted: false,
    order: 3,
  },
  {
    id: 'enterprise-software',
    title: 'Enterprise Software',
    tagline: 'Multi-tenant SaaS and internal tools for enterprise clients.',
    description: 'I have built multi-tenant platforms serving 14 enterprise clients from a single deployment. PostgreSQL RLS for data isolation, Spring Batch for bulk processing, and blue/green deployments for zero-downtime releases.',
    icon: 'pi pi-building',
    deliverables: [
      { text: 'Multi-tenant architecture with RLS' },
      { text: 'Role-based access control (RBAC)' },
      { text: 'Audit logging & compliance reports' },
      { text: 'Spring Batch bulk processing' },
      { text: 'Zero-downtime deployment strategy' },
    ],
    engagement: 'project',
    duration: '8–24 weeks',
    featured: true,
    highlighted: false,
    badge: 'Speciality',
    order: 4,
  },
  {
    id: 'ai-integrations',
    title: 'AI Integrations',
    tagline: 'LLM pipelines that solve real business problems, not demos.',
    description: 'OpenAI function calling, Spring Batch document pipelines, pgvector semantic search, and confidence-scored human review queues. I have reduced manual review time by 70% in production with these patterns.',
    icon: 'pi pi-microchip-ai',
    deliverables: [
      { text: 'OpenAI / Anthropic API integration' },
      { text: 'Document processing pipeline' },
      { text: 'pgvector semantic search' },
      { text: 'Human-in-the-loop review queue' },
      { text: 'Token cost optimisation' },
    ],
    engagement: 'project',
    duration: '3–10 weeks',
    featured: false,
    highlighted: false,
    order: 5,
  },
  {
    id: 'cloud-deployment',
    title: 'Cloud Deployment',
    tagline: 'AWS infrastructure that scales without surprises on the bill.',
    description: 'Terraform-managed AWS infrastructure: ECS Fargate, RDS Multi-AZ, ElastiCache, CloudFront, and Route 53. Blue/green deployments, auto-scaling policies, and CloudWatch alarms configured from the start.',
    icon: 'pi pi-cloud-upload',
    deliverables: [
      { text: 'Terraform IaC for all resources' },
      { text: 'ECS Fargate + RDS + ElastiCache' },
      { text: 'Blue/green deployment pipeline' },
      { text: 'Auto-scaling & CloudWatch alarms' },
      { text: 'Cost optimisation review' },
    ],
    engagement: 'project',
    duration: '1–3 weeks',
    featured: false,
    highlighted: false,
    order: 6,
  },
  {
    id: 'performance-optimization',
    title: 'Performance Optimisation',
    tagline: 'Find and fix the bottlenecks before your users do.',
    description: 'I profile, diagnose, and fix slow APIs and databases. Composite indexes, materialised views, N+1 query elimination, connection pool tuning, and Redis caching. I have taken endpoints from 2.8s to 8ms in production.',
    icon: 'pi pi-gauge',
    deliverables: [
      { text: 'APM profiling & bottleneck report' },
      { text: 'Database query optimisation' },
      { text: 'Caching strategy implementation' },
      { text: 'Before/after benchmark report' },
      { text: 'Monitoring dashboard setup' },
    ],
    engagement: 'hourly',
    duration: '1–2 weeks',
    featured: false,
    highlighted: false,
    order: 7,
  },
  {
    id: 'code-review',
    title: 'Code Review',
    tagline: 'A senior engineer\'s eye on your codebase before it ships.',
    description: 'Structured review covering security vulnerabilities, performance anti-patterns, test coverage gaps, and architectural concerns. Written report with prioritised findings and specific remediation steps — not vague suggestions.',
    icon: 'pi pi-search',
    deliverables: [
      { text: 'Security vulnerability scan' },
      { text: 'Performance anti-pattern audit' },
      { text: 'Architecture review report' },
      { text: 'Prioritised findings document' },
      { text: 'Remediation recommendations' },
    ],
    engagement: 'hourly',
    duration: '2–5 days',
    featured: false,
    highlighted: false,
    order: 8,
  },
  {
    id: 'technical-consulting',
    title: 'Technical Consulting',
    tagline: 'Architecture decisions made with someone who has shipped them.',
    description: 'Technology selection, system design reviews, team mentoring, and pre-launch technical audits. I give direct opinions based on 7+ years of production experience — not hedged recommendations designed to avoid accountability.',
    icon: 'pi pi-comments',
    deliverables: [
      { text: 'Architecture design session' },
      { text: 'Technology selection guidance' },
      { text: 'System design document review' },
      { text: 'Team technical mentoring' },
      { text: 'Pre-launch audit & sign-off' },
    ],
    engagement: 'consulting',
    duration: 'Ongoing',
    featured: false,
    highlighted: false,
    order: 9,
  },
]

export const SERVICE_ENGAGEMENT_CONFIG: Record<string, { label: string; color: string; bg: string }> = {
  project:    { label: 'Fixed Price',  color: '#6366f1', bg: 'rgba(99,102,241,0.1)'  },
  hourly:     { label: 'Hourly',       color: '#10b981', bg: 'rgba(16,185,129,0.1)'  },
  retainer:   { label: 'Retainer',     color: '#f59e0b', bg: 'rgba(245,158,11,0.1)'  },
  consulting: { label: 'Consulting',   color: '#8b5cf6', bg: 'rgba(139,92,246,0.1)'  },
}

export const SERVICE_GRADIENTS: Record<number, { from: string; to: string; glow: string }> = {
  0: { from: '#6366f1', to: '#8b5cf6', glow: 'rgba(99,102,241,0.2)'  },
  1: { from: '#10b981', to: '#06b6d4', glow: 'rgba(16,185,129,0.2)'  },
  2: { from: '#8b5cf6', to: '#ec4899', glow: 'rgba(139,92,246,0.2)'  },
  3: { from: '#6366f1', to: '#06b6d4', glow: 'rgba(99,102,241,0.2)'  },
  4: { from: '#10b981', to: '#6366f1', glow: 'rgba(16,185,129,0.2)'  },
  5: { from: '#f59e0b', to: '#ef4444', glow: 'rgba(245,158,11,0.2)'  },
  6: { from: '#06b6d4', to: '#6366f1', glow: 'rgba(6,182,212,0.2)'   },
  7: { from: '#8b5cf6', to: '#6366f1', glow: 'rgba(139,92,246,0.2)'  },
  8: { from: '#10b981', to: '#8b5cf6', glow: 'rgba(16,185,129,0.2)'  },
}
