import type { SkillGroup } from '@/types'

export const SKILL_GROUPS: SkillGroup[] = [
  {
    category: 'backend',
    label: 'Backend',
    description: 'The core. Where business logic lives, performance is won or lost, and bad decisions compound for years.',
    icon: 'pi pi-server',
    skills: [
      {
        id: 'java',
        name: 'Java 21',
        category: 'backend',
        level: 'expert',
        yearsOfExperience: 7,
        context: 'Virtual threads, records, sealed classes. Primary language across every enterprise system I\'ve shipped.',
        featured: true,
      },
      {
        id: 'spring-boot',
        name: 'Spring Boot',
        category: 'backend',
        level: 'expert',
        yearsOfExperience: 6,
        context: 'Spring Security, Data JPA, WebFlux, Batch. Built multi-tenant platforms and high-throughput APIs.',
        featured: true,
      },
      {
        id: 'rest-apis',
        name: 'REST APIs',
        category: 'backend',
        level: 'expert',
        yearsOfExperience: 7,
        context: 'Versioning, pagination, error contracts, OpenAPI docs. Designed APIs consumed by 6+ enterprise clients.',
        featured: false,
      },
      {
        id: 'microservices',
        name: 'Microservices',
        category: 'backend',
        level: 'advanced',
        yearsOfExperience: 4,
        context: 'Service decomposition, inter-service communication, distributed tracing, saga patterns.',
        featured: false,
      },
    ],
  },
  {
    category: 'frontend',
    label: 'Frontend',
    description: 'I build the UI that clients actually use — fast, accessible, and precise enough that nobody notices the engineering.',
    icon: 'pi pi-desktop',
    skills: [
      {
        id: 'vue',
        name: 'Vue 3',
        category: 'frontend',
        level: 'expert',
        yearsOfExperience: 3,
        context: 'Composition API, Pinia, Vue Router, SSR. This portfolio is built on it.',
        featured: true,
      },
      {
        id: 'angular',
        name: 'Angular',
        category: 'frontend',
        level: 'advanced',
        yearsOfExperience: 3,
        context: 'Components, RxJS, Angular Material, Reactive Forms, routing.',
        featured: true
      },
      {
        id: 'typescript',
        name: 'TypeScript',
        category: 'frontend',
        level: 'advanced',
        yearsOfExperience: 4,
        context: 'Strict mode, generics, utility types, discriminated unions. No any in production.',
        featured: true,
      },
      {
        id: 'javascript',
        name: 'JavaScript',
        category: 'frontend',
        level: 'expert',
        yearsOfExperience: 6,
        context: 'ES2024, async patterns, performance profiling, Web APIs.',
        featured: false,
      },
      {
        id: 'primevue',
        name: 'PrimeVue',
        category: 'frontend',
        level: 'advanced',
        yearsOfExperience: 2,
        context: 'Custom themes, PassThrough API, enterprise component systems.',
        featured: false,
      },
    ],
  },
  {
    category: 'database',
    label: 'Database',
    description: 'Data modelling is where most systems quietly fail. I treat schema design as a first-class engineering decision.',
    icon: 'pi pi-database',
    skills: [
      {
        id: 'bigquery',
        name: 'BigQuery',
        category: 'database',
        level: 'expert',
        yearsOfExperience: 4,
        context: 'Large-scale analytics, SQL optimisation, partitioning, ETL, dashboards.',
        featured: true,
      },
      {
        id: 'postgresql',
        name: 'PostgreSQL',
        category: 'database',
        level: 'advanced',
        yearsOfExperience: 4,
        context: 'Query optimisation, indexing strategies, partitioning, JSONB, window functions.',
        featured: true,
      },
      {
        id: 'mysql',
        name: 'MySQL',
        category: 'database',
        level: 'expert',
        yearsOfExperience: 6,
        context: 'Query optimisation, indexing, joins, stored procedures, transactions.',
        featured: true,
      },
      {
        id: 'oracle',
        name: 'Oracle DB',
        category: 'database',
        level: 'advanced',
        yearsOfExperience: 4,
        context: 'PL/SQL, execution plans, AWR reports, enterprise data warehousing.',
        featured: true,
      },
    ],
  },
  {
    category: 'cloud',
    label: 'Google Cloud & AWS',
    description: 'Infrastructure is code. I design for resilience, cost efficiency, and the ability to scale without a rewrite.',
    icon: 'pi pi-cloud',
    skills: [
      {
        id: 'gcp',
        name: 'Google Cloud',
        category: 'cloud',
        level: 'intermediate',
        yearsOfExperience: 2,
        context: 'Cloud Run, Compute Engine, Cloud Storage, IAM, Cloud Functions.',
        featured: true,
      },
      {
        id: 'aws',
        name: 'AWS',
        category: 'cloud',
        level: 'intermediate',
        yearsOfExperience: 2,
        context: 'EC2, ECS, Lambda, RDS, S3, CloudFront, SQS, SNS, IAM, VPC. 3 production cloud deployments.',
        featured: true,
      },
    ],
  },
  {
    category: 'devops',
    label: 'DevOps',
    description: 'Shipping is a feature. I own the pipeline from commit to production — fast, repeatable, and observable.',
    icon: 'pi pi-cog',
    skills: [
      {
        id: 'docker',
        name: 'Docker',
        category: 'devops',
        level: 'advanced',
        yearsOfExperience: 4,
        context: 'Multi-stage builds, compose, image optimisation, security scanning.',
        featured: true,
      },
      {
        id: 'kubernetes',
        name: 'Kubernetes',
        category: 'devops',
        level: 'intermediate',
        yearsOfExperience: 2,
        context: 'Deployments, services, ingress, HPA, config maps, EKS on AWS.',
        featured: true,
      },
      {
        id: 'jenkins',
        name: 'Jenkins',
        category: 'devops',
        level: 'advanced',
        yearsOfExperience: 4,
        context: 'Declarative pipelines, shared libraries, parallel stages. Cut deploy time from 4h to 18min.',
        featured: false,
      },
      {
        id: 'gradle',
        name: 'Gradle',
        category: 'devops',
        level: 'advanced',
        yearsOfExperience: 5,
        context: 'Multi-project builds, custom tasks, dependency management, build caching.',
        featured: false,
      },
      {
        id: 'maven',
        name: 'Maven',
        category: 'devops',
        level: 'advanced',
        yearsOfExperience: 6,
        context: 'Multi-module projects, custom plugins, release management.',
        featured: false,
      },
    ],
  },
  {
    category: 'ai',
    label: 'AI & LLMs',
    description: 'Not a buzzword — a genuine force multiplier. I integrate AI where it eliminates toil and keeps judgment human.',
    icon: 'pi pi-microchip-ai',
    skills: [
      {
        id: 'openai',
        name: 'OpenAI API',
        category: 'ai',
        level: 'intermediate',
        yearsOfExperience: 2,
        context: 'GPT-4o, embeddings, function calling, RAG pipelines, token optimisation.',
        featured: true,
      },
    ],
  },
  {
    category: 'tools',
    label: 'Tools',
    description: 'The craft layer — version control, collaboration, and the habits that keep a codebase healthy over years.',
    icon: 'pi pi-wrench',
    skills: [
      {
        id: 'git',
        name: 'Git',
        category: 'tools',
        level: 'expert',
        yearsOfExperience: 7,
        context: 'Branching strategies, rebase workflows, bisect, reflog. Git is a thinking tool, not just version control.',
        featured: true,
      },
    ],
  },
]

export const SKILL_LEVEL_CONFIG = {
  expert:       { label: 'Expert',       color: '#6366f1', bg: 'rgba(99,102,241,0.12)'  },
  advanced:     { label: 'Advanced',     color: '#10b981', bg: 'rgba(16,185,129,0.12)'  },
  intermediate: { label: 'Intermediate', color: '#f59e0b', bg: 'rgba(245,158,11,0.12)'  },
  learning:     { label: 'Learning',     color: '#22d3ee', bg: 'rgba(34,211,238,0.12)'  },
} as const

export const CATEGORY_COLORS: Record<string, { from: string; to: string; glow: string }> = {
  backend:  { from: '#6366f1', to: '#8b5cf6', glow: 'rgba(99,102,241,0.2)'  },
  frontend: { from: '#06b6d4', to: '#6366f1', glow: 'rgba(6,182,212,0.2)'   },
  database: { from: '#10b981', to: '#06b6d4', glow: 'rgba(16,185,129,0.2)'  },
  cloud:    { from: '#f59e0b', to: '#ef4444', glow: 'rgba(245,158,11,0.2)'  },
  devops:   { from: '#8b5cf6', to: '#ec4899', glow: 'rgba(139,92,246,0.2)'  },
  ai:       { from: '#22d3ee', to: '#10b981', glow: 'rgba(34,211,238,0.2)'  },
  tools:    { from: '#a78bfa', to: '#6366f1', glow: 'rgba(167,139,250,0.2)' },
}
