import type { Testimonial } from '@/types'

// Extended type — adds fields the base Testimonial interface doesn't have.
// Replace with real data when client testimonials are collected.
export interface TestimonialFull extends Testimonial {
  rating: 1 | 2 | 3 | 4 | 5
  companyLogo?: string        // path to logo asset, e.g. '/logos/acme.svg'
  companyUrl?: string
  projectRef?: string         // which project this relates to
  engagement?: string         // e.g. 'Full Stack Development', '6 months'
  location?: string
}

export const TESTIMONIALS: TestimonialFull[] = [
  {
    id: 'testimonial-1',
    quote: "Yash delivered the multi-tenant SaaS platform on time and under budget. What impressed me most was his ability to make the right architectural call early — the PostgreSQL RLS approach saved us months of rework. He's the kind of engineer who thinks about the business problem, not just the code.",
    author: 'Placeholder — CTO',
    role: 'Chief Technology Officer',
    company: 'Enterprise SaaS Client',
    avatar: undefined,
    linkedIn: undefined,
    rating: 5,
    companyLogo: undefined,
    companyUrl: undefined,
    projectRef: 'Multi-Tenant SaaS Platform',
    engagement: 'Full Stack Development · 6 months',
    location: 'Mumbai, India',
    featured: true,
    order: 1,
  },
  {
    id: 'testimonial-2',
    quote: "The LLM document pipeline Yash built reduced our manual review workload by 70%. He understood the business constraints — token costs, accuracy thresholds, compliance requirements — and built a system that actually works in production, not just in a demo.",
    author: 'Placeholder — VP Engineering',
    role: 'VP of Engineering',
    company: 'Legal Services Firm',
    avatar: undefined,
    linkedIn: undefined,
    rating: 5,
    companyLogo: undefined,
    companyUrl: undefined,
    projectRef: 'LLM Document Processing Pipeline',
    engagement: 'AI Integration · 3 months',
    location: 'Bangalore, India',
    featured: true,
    order: 2,
  },
  {
    id: 'testimonial-3',
    quote: "Our logistics platform was on the verge of losing a major enterprise client due to SLA violations. Yash redesigned the tracking system with Kafka event streaming in 8 weeks. Location staleness went from 90 seconds to under 3 seconds. The client renewed. That's the only metric that matters.",
    author: 'Placeholder — Head of Product',
    role: 'Head of Product',
    company: 'Logistics Technology Company',
    avatar: undefined,
    linkedIn: undefined,
    rating: 5,
    companyLogo: undefined,
    companyUrl: undefined,
    projectRef: 'Real-Time Logistics Tracking',
    engagement: 'Backend Architecture · 8 months',
    location: 'Delhi, India',
    featured: true,
    order: 3,
  },
  {
    id: 'testimonial-4',
    quote: "Yash built our payroll compliance engine from scratch. We had two payroll errors in the previous year from our Excel-based process. Since deployment, zero errors across ₹40 Cr monthly. He also documented everything thoroughly — the system is maintainable by our internal team.",
    author: 'Placeholder — Finance Director',
    role: 'Finance Director',
    company: 'HR & Payroll SaaS',
    avatar: undefined,
    linkedIn: undefined,
    rating: 5,
    companyLogo: undefined,
    companyUrl: undefined,
    projectRef: 'Payroll Compliance Engine',
    engagement: 'Enterprise Software · 5 months',
    location: 'Pune, India',
    featured: false,
    order: 4,
  },
  {
    id: 'testimonial-5',
    quote: "We brought Yash in for a technical consulting engagement before our Series A. He reviewed our architecture, identified three critical scalability bottlenecks, and gave us a clear remediation roadmap. His recommendations were specific and actionable — not the vague 'it depends' answers you get from most consultants.",
    author: 'Placeholder — Founder & CEO',
    role: 'Founder & CEO',
    company: 'B2B Fintech Startup',
    avatar: undefined,
    linkedIn: undefined,
    rating: 5,
    companyLogo: undefined,
    companyUrl: undefined,
    projectRef: 'Technical Consulting',
    engagement: 'Architecture Review · 2 weeks',
    location: 'Hyderabad, India',
    featured: false,
    order: 5,
  },
  {
    id: 'testimonial-6',
    quote: "The code review Yash did on our payment service found a race condition that would have caused duplicate charges under load. We hadn't caught it in 6 months of development. The written report was detailed, prioritised, and had specific fixes — not just a list of problems.",
    author: 'Placeholder — Engineering Lead',
    role: 'Engineering Lead',
    company: 'Payments Startup',
    avatar: undefined,
    linkedIn: undefined,
    rating: 5,
    companyLogo: undefined,
    companyUrl: undefined,
    projectRef: 'Code Review',
    engagement: 'Code Review · 3 days',
    location: 'Chennai, India',
    featured: false,
    order: 6,
  },
  {
    id: 'testimonial-7',
    quote: "Yash migrated our monolith to AWS ECS with zero downtime. He set up Terraform, Jenkins CI/CD, blue/green deployments, and CloudWatch monitoring in 3 weeks. Our deployment time went from 2 hours of manual steps to 18 minutes fully automated. The infrastructure is solid.",
    author: 'Placeholder — DevOps Manager',
    role: 'DevOps Manager',
    company: 'E-Commerce Platform',
    avatar: undefined,
    linkedIn: undefined,
    rating: 5,
    companyLogo: undefined,
    companyUrl: undefined,
    projectRef: 'Cloud Deployment',
    engagement: 'Cloud Infrastructure · 3 weeks',
    location: 'Ahmedabad, India',
    featured: false,
    order: 7,
  },
  {
    id: 'testimonial-8',
    quote: "We hired Yash to optimise our dashboard API that was taking 2.8 seconds to load. He profiled it, added materialised views and Redis caching, and got it to 8ms. He also left us with a monitoring setup so we'd catch regressions early. Exactly what we needed.",
    author: 'Placeholder — Tech Lead',
    role: 'Tech Lead',
    company: 'Analytics SaaS',
    avatar: undefined,
    linkedIn: undefined,
    rating: 5,
    companyLogo: undefined,
    companyUrl: undefined,
    projectRef: 'Performance Optimisation',
    engagement: 'Performance Audit · 2 weeks',
    location: 'Kolkata, India',
    featured: false,
    order: 8,
  },
]

// Duplicate for seamless infinite scroll
export const TESTIMONIALS_LOOP = [...TESTIMONIALS, ...TESTIMONIALS]
