// ─────────────────────────────────────────────────────────────────────────────
// src/content/skills/index.ts
// Single source of truth for all skills.
// Each SkillGroup is self-contained — gradient lives on the group.
// CATEGORY_COLORS and SKILL_LEVEL_CONFIG are derived — never edited manually.
// To add a skill: add one object to the relevant group's skills array.
// To add a category: add one SkillGroup object. Nothing else.
// ─────────────────────────────────────────────────────────────────────────────
import type { SkillGroup } from '@/types'

export const SKILL_GROUPS: SkillGroup[] = [
  // ── Frontend ───────────────────────────────────────────────────────────────
  {
    category: 'frontend',
    label: 'Frontend',
    description: 'I build the UI that clients actually use — fast, accessible, and precise enough that nobody notices the engineering.',
    icon: 'pi pi-desktop',
    gradient: { from: '#06b6d4', to: '#6366f1', glow: 'rgba(6,182,212,0.2)' },
    skills: [
      {
        id: 'vue',
        name: 'Vue 3',
        category: 'frontend',
        level: 'expert',
        yearsOfExperience: 3,
        context: 'Composition API, Pinia, Vue Router, SSR. This portfolio is built on it.',
        featured: true,
      },
      {
        id: 'angular',
        name: 'Angular',
        category: 'frontend',
        level: 'advanced',
        yearsOfExperience: 3,
        context: 'Components, RxJS, Angular Material, Reactive Forms, routing.',
        featured: true,
      },
      {
        id: 'gwt',
        name: 'Google Web Toolkit (GWT)',
        category: 'frontend',
        level: 'advanced',
        yearsOfExperience: 2,
        context: 'Enterprise web applications, UiBinder, MVP pattern, GWT RPC, custom components, Java-based frontend development.',
        featured: false,
      },
      {
        id: 'typescript',
        name: 'TypeScript',
        category: 'frontend',
        level: 'advanced',
        yearsOfExperience: 4,
        context: 'Strict mode, generics, utility types, discriminated unions. No any in production.',
        featured: true,
      },
      {
        id: 'javascript',
        name: 'JavaScript',
        category: 'frontend',
        level: 'expert',
        yearsOfExperience: 6,
        context: 'ES2024, async patterns, performance profiling, Web APIs.',
        featured: false,
      },
      {
        id: 'primevue',
        name: 'PrimeVue',
        category: 'frontend',
        level: 'advanced',
        yearsOfExperience: 2,
        context: 'Custom themes, PassThrough API, enterprise component systems.',
        featured: false,
      },
      {
        id: 'tailwind',
        name: 'Tailwind CSS',
        category: 'frontend',
        level: 'learning',
        yearsOfExperience: 3,
        context: 'Utility-first styling, custom design systems, responsive layouts.',
        featured: false,
      },
    ],
  },

  // ── Backend ────────────────────────────────────────────────────────────────
  {
    category: 'backend',
    label: 'Backend',
    description: 'The core. Where business logic lives, performance is won or lost, and bad decisions compound for years.',
    icon: 'pi pi-server',
    gradient: { from: '#6366f1', to: '#8b5cf6', glow: 'rgba(99,102,241,0.2)' },
    skills: [
      {
        id: 'java',
        name: 'Java 21',
        category: 'backend',
        level: 'expert',
        yearsOfExperience: 7,
        context: 'Virtual threads, records, sealed classes. Primary language across every enterprise system I\'ve shipped.',
        featured: true,
      },
      {
        id: 'spring-boot',
        name: 'Spring Boot',
        category: 'backend',
        level: 'expert',
        yearsOfExperience: 6,
        context: 'Spring Security, Data JPA, WebFlux, Batch. Built multi-tenant platforms and high-throughput APIs.',
        featured: true,
      },
      {
        id: 'spring-batch',
        name: 'Spring Batch',
        category: 'backend',
        level: 'intermediate',
        yearsOfExperience: 2,
        context: 'Parallel chunk processing, job restartability, large-scale ETL pipelines.',
        featured: false,
      },
      {
        id: 'rest-apis',
        name: 'REST APIs',
        category: 'backend',
        level: 'expert',
        yearsOfExperience: 7,
        context: 'Versioning, pagination, error contracts (RFC 7807), OpenAPI docs. Designed APIs consumed by 6+ enterprise clients.',
        featured: false,
      },
      {
        id: 'kafka',
        name: 'Apache Kafka',
        category: 'backend',
        level: 'learning',
        yearsOfExperience: 1,
        context: 'Event streaming, partitioning strategies, consumer groups, exactly-once semantics.',
        featured: true,
      },
      {
        id: 'redis',
        name: 'Redis',
        category: 'backend',
        level: 'learning',
        yearsOfExperience: 2,
        context: 'Caching, distributed locking, pub/sub, rate limiting, session storage.',
        featured: false,
      },
      {
        id: 'microservices',
        name: 'Microservices',
        category: 'backend',
        level: 'advanced',
        yearsOfExperience: 4,
        context: 'Service decomposition, inter-service communication, distributed tracing, saga patterns.',
        featured: false,
      },
    ],
  },

  // ── Cloud ──────────────────────────────────────────────────────────────────
  {
    category: 'cloud',
    label: 'Cloud',
    description: 'Infrastructure is code. I design for resilience, cost efficiency, and the ability to scale without a rewrite.',
    icon: 'pi pi-cloud',
    gradient: { from: '#f59e0b', to: '#ef4444', glow: 'rgba(245,158,11,0.2)' },
    skills: [
      {
        id: 'aws',
        name: 'AWS',
        category: 'cloud',
        level: 'intermediate',
        yearsOfExperience: 3,
        context: 'EC2, ECS Fargate, EKS, Lambda, RDS, S3, CloudFront, SQS, SNS, IAM, VPC. 3 production deployments.',
        featured: true,
      },
      {
        id: 'gcp',
        name: 'Google Cloud',
        category: 'cloud',
        level: 'intermediate',
        yearsOfExperience: 2,
        context: 'Cloud Run, Compute Engine, Cloud Storage, BigQuery, IAM, Cloud Functions.',
        featured: true,
      },
      {
        id: 'nginx',
        name: 'Nginx',
        category: 'cloud',
        level: 'intermediate',
        yearsOfExperience: 4,
        context: 'Reverse proxy, load balancing, SSL termination, rate limiting.',
        featured: false,
      },
    ],
  },

  // ── AI & LLMs ──────────────────────────────────────────────────────────────
  {
    category: 'ai',
    label: 'AI & LLMs',
    description: 'Not a buzzword — a genuine force multiplier. I integrate AI where it eliminates toil and keeps judgment human.',
    icon: 'pi pi-microchip-ai',
    gradient: { from: '#22d3ee', to: '#10b981', glow: 'rgba(34,211,238,0.2)' },
    skills: [
      {
        id: 'openai',
        name: 'OpenAI API',
        category: 'ai',
        level: 'intermediate',
        yearsOfExperience: 1,
        context: 'GPT-4o, embeddings, function calling, RAG pipelines, token optimisation.',
        featured: true,
      },
      {
        id: 'langchain',
        name: 'LangChain',
        category: 'ai',
        level: 'learning',
        yearsOfExperience: 1,
        context: 'Chains, agents, document loaders, vector store integrations.',
        featured: false,
      },
      {
        id: 'prompt-engineering',
        name: 'Prompt Engineering',
        category: 'ai',
        level: 'intermediate',
        yearsOfExperience: 2,
        context: 'Structured output, few-shot prompting, chain-of-thought, cost optimisation.',
        featured: false,
      },
    ],
  },

  // ── Databases ──────────────────────────────────────────────────────────────
  {
    category: 'database',
    label: 'Databases',
    description: 'Data modelling is where most systems quietly fail. I treat schema design as a first-class engineering decision.',
    icon: 'pi pi-database',
    gradient: { from: '#10b981', to: '#06b6d4', glow: 'rgba(16,185,129,0.2)' },
    skills: [
      {
        id: 'postgresql',
        name: 'PostgreSQL',
        category: 'database',
        level: 'advanced',
        yearsOfExperience: 4,
        context: 'Query optimisation, indexing strategies, partitioning, JSONB, window functions, RLS.',
        featured: true,
      },
      {
        id: 'mysql',
        name: 'MySQL',
        category: 'database',
        level: 'expert',
        yearsOfExperience: 6,
        context: 'Query optimisation, indexing, joins, stored procedures, transactions.',
        featured: true,
      },
      {
        id: 'oracle',
        name: 'Oracle DB',
        category: 'database',
        level: 'advanced',
        yearsOfExperience: 4,
        context: 'PL/SQL, execution plans, AWR reports, enterprise data warehousing.',
        featured: true,
      },
      {
        id: 'bigquery',
        name: 'BigQuery',
        category: 'database',
        level: 'expert',
        yearsOfExperience: 4,
        context: 'Large-scale analytics, SQL optimisation, partitioning, ETL, dashboards.',
        featured: true,
      },
    ],
  },

  // ── DevOps ─────────────────────────────────────────────────────────────────
  {
    category: 'devops',
    label: 'DevOps',
    description: 'Shipping is a feature. I own the pipeline from commit to production — fast, repeatable, and observable.',
    icon: 'pi pi-cog',
    gradient: { from: '#8b5cf6', to: '#ec4899', glow: 'rgba(139,92,246,0.2)' },
    skills: [
      {
        id: 'docker',
        name: 'Docker',
        category: 'devops',
        level: 'intermediate',
        yearsOfExperience: 1,
        context: 'Multi-stage builds, compose, image optimisation, security scanning.',
        featured: true,
      },
      {
        id: 'kubernetes',
        name: 'Kubernetes',
        category: 'devops',
        level: 'intermediate',
        yearsOfExperience: 2,
        context: 'Deployments, services, ingress, HPA, config maps, EKS on AWS.',
        featured: true,
      },
      {
        id: 'jenkins',
        name: 'Jenkins',
        category: 'devops',
        level: 'advanced',
        yearsOfExperience: 4,
        context: 'Declarative pipelines, shared libraries, parallel stages. Cut deploy time from 4h to 18min.',
        featured: false,
      },
      {
        id: 'gradle',
        name: 'Gradle',
        category: 'devops',
        level: 'advanced',
        yearsOfExperience: 2,
        context: 'Multi-project builds, custom tasks, dependency management, build caching.',
        featured: false,
      },
      {
        id: 'maven',
        name: 'Maven',
        category: 'devops',
        level: 'advanced',
        yearsOfExperience: 5,
        context: 'Multi-module projects, custom plugins, release management.',
        featured: false,
      },
      {
        id: 'git',
        name: 'Git',
        category: 'devops',
        level: 'expert',
        yearsOfExperience: 7,
        context: 'Branching strategies, rebase workflows, bisect, reflog. Git is a thinking tool, not just version control.',
        featured: true,
      },
    ],
  },

  // ── Testing ────────────────────────────────────────────────────────────────
  {
    category: 'testing',
    label: 'Testing',
    description: 'Tests are the only proof that software does what you think it does. I write them before they\'re asked for.',
    icon: 'pi pi-check-circle',
    gradient: { from: '#a78bfa', to: '#6366f1', glow: 'rgba(167,139,250,0.2)' },
    skills: [
      {
        id: 'junit',
        name: 'JUnit 5',
        category: 'testing',
        level: 'intermediate',
        yearsOfExperience: 2,
        context: 'Parameterised tests, extensions, lifecycle hooks, nested test classes.',
        featured: true,
      },
      {
        id: 'mockito',
        name: 'Mockito',
        category: 'testing',
        level: 'learning',
        yearsOfExperience: 2,
        context: 'Mocking, stubbing, argument captors, spy objects, verification.',
        featured: true,
      },
    ],
  },

  // ── Architecture ───────────────────────────────────────────────────────────
  // {
  //   category: 'architecture',
  //   label: 'Architecture',
  //   description: 'Good architecture is invisible. Bad architecture is all you talk about. I\'ve learned the difference the hard way.',
  //   icon: 'pi pi-sitemap',
  //   gradient: { from: '#f97316', to: '#f59e0b', glow: 'rgba(249,115,22,0.2)' },
  //   skills: [
  //     {
  //       id: 'domain-driven-design',
  //       name: 'Domain-Driven Design',
  //       category: 'architecture',
  //       level: 'advanced',
  //       yearsOfExperience: 4,
  //       context: 'Bounded contexts, aggregates, domain events, ubiquitous language.',
  //       featured: true,
  //     },
  //     {
  //       id: 'event-sourcing',
  //       name: 'Event Sourcing',
  //       category: 'architecture',
  //       level: 'intermediate',
  //       yearsOfExperience: 2,
  //       context: 'Append-only event logs, projections, replay capability, audit trails.',
  //       featured: true,
  //     },
  //     {
  //       id: 'cqrs',
  //       name: 'CQRS',
  //       category: 'architecture',
  //       level: 'intermediate',
  //       yearsOfExperience: 2,
  //       context: 'Command/query separation, read model optimisation, eventual consistency.',
  //       featured: false,
  //     },
  //     {
  //       id: 'multi-tenancy',
  //       name: 'Multi-Tenancy',
  //       category: 'architecture',
  //       level: 'advanced',
  //       yearsOfExperience: 3,
  //       context: 'Shared-schema with RLS, schema-per-tenant, data isolation patterns.',
  //       featured: true,
  //     },
  //     {
  //       id: 'api-design',
  //       name: 'API Design',
  //       category: 'architecture',
  //       level: 'expert',
  //       yearsOfExperience: 7,
  //       context: 'RESTful conventions, versioning strategies, backward compatibility, OpenAPI.',
  //       featured: false,
  //     },
  //   ],
  // },

  // ── Soft Skills ────────────────────────────────────────────────────────────
  {
    category: 'soft-skills',
    label: 'Soft Skills',
    description: 'Technical skill gets you hired. Communication, ownership, and judgment are what make you irreplaceable.',
    icon: 'pi pi-users',
    gradient: { from: '#ec4899', to: '#8b5cf6', glow: 'rgba(236,72,153,0.2)' },
    skills: [
      {
        id: 'technical-communication',
        name: 'Technical Communication',
        category: 'soft-skills',
        level: 'expert',
        yearsOfExperience: 7,
        context: 'Writing ADRs, RFCs, post-mortems, and technical specs that non-engineers can act on.',
        featured: true,
      },
      {
        id: 'client-management',
        name: 'Client Management',
        category: 'soft-skills',
        level: 'advanced',
        yearsOfExperience: 4,
        context: 'Scoping engagements, managing expectations, delivering hard news early.',
        featured: true,
      },
      {
        id: 'mentoring',
        name: 'Mentoring',
        category: 'soft-skills',
        level: 'advanced',
        yearsOfExperience: 5,
        context: 'Code reviews, pair programming, establishing team engineering standards.',
        featured: false,
      },
      {
        id: 'problem-decomposition',
        name: 'Problem Decomposition',
        category: 'soft-skills',
        level: 'expert',
        yearsOfExperience: 7,
        context: 'Breaking ambiguous requirements into shippable increments without losing the big picture.',
        featured: false,
      },
    ],
  },
]

// ── Derived maps — never edit these manually ──────────────────────────────────

export const CATEGORY_COLORS = Object.fromEntries(
  SKILL_GROUPS.map(g => [g.category, g.gradient])
) as Record<string, SkillGroup['gradient']>

export const SKILL_LEVEL_CONFIG = {
  expert:       { label: 'Expert',       color: '#6366f1', bg: 'rgba(99,102,241,0.12)'  },
  advanced:     { label: 'Advanced',     color: '#10b981', bg: 'rgba(16,185,129,0.12)'  },
  intermediate: { label: 'Intermediate', color: '#f59e0b', bg: 'rgba(245,158,11,0.12)'  },
  learning:     { label: 'Learning',     color: '#22d3ee', bg: 'rgba(34,211,238,0.12)'  },
} as const
